package com.dbobjekts.vendors.mysql

import com.dbobjekts.vendors.VendorSpecificProperties

class MariaDBProperties:VendorSpecificProperties {

    override fun sequencePattern(): String = ""

    override fun columnTypeCanBeAutoGeneratedKey(columnType: String): Boolean = MariaDBDataTypeMapper.numericTypes.contains(columnType.lowercase())

    override fun supportsJoinsInUpdateAndDelete(): Boolean = true

}
