package com.dbobjekts.metadata.column


enum class ColumnType {
    VARCHAR, LONG, INTEGER, BYTE_ARRAY, BLOB, CLOB, BYTE, BOOLEAN, NUMBER_AS_BOOLEAN, DOUBLE, FLOAT, BIGDECIMAL, DATE, TIME, DATETIME, TIMESTAMP, OFFSET_DATETIME
}
