package com.dbobjekts.vendors.h2

import com.dbobjekts.vendors.VendorSpecificProperties

class H2Properties:VendorSpecificProperties {

    override fun sequencePattern(): String = "call nextval('%s')"

    override fun columnTypeCanBeAutoGeneratedKey(columnType: String): Boolean = H2DataTypeMapper.numericTypes.contains(columnType.lowercase())

    override fun supportsJoinsInUpdateAndDelete(): Boolean = false

}
