package com.dbobjekts.postgresql.testdb.core
import com.dbobjekts.metadata.Schema

/**            
 * Auto-generated metadata object representing a schema consisting of one or more tables.
 *
 * Do not edit this file manually! Always use [com.dbobjekts.codegen.CodeGenerator] when the metadata model is no longer in sync with the database.             
*/
object Core : Schema("core", listOf(Address, AllTypesNil, Composite, CompositeForeignKey, Country, Department, Employee, EmployeeAddress, EmployeeDepartment)){

    /** 
     * Refers to metadata object for table address 
     */
    val address = Address
        
    /** 
     * Refers to metadata object for table all_types_nil 
     */
    val allTypesNil = AllTypesNil
        
    /** 
     * Refers to metadata object for table composite 
     */
    val composite = Composite
        
    /** 
     * Refers to metadata object for table composite_foreign_key 
     */
    val compositeForeignKey = CompositeForeignKey
        
    /** 
     * Refers to metadata object for table country 
     */
    val country = Country
        
    /** 
     * Refers to metadata object for table department 
     */
    val department = Department
        
    /** 
     * Refers to metadata object for table employee 
     */
    val employee = Employee
        
    /** 
     * Refers to metadata object for table employee_address 
     */
    val employeeAddress = EmployeeAddress
        
    /** 
     * Refers to metadata object for table employee_department 
     */
    val employeeDepartment = EmployeeDepartment
        
}
      