package com.dbobjekts.mariadb.testdb.nation

import com.dbobjekts.api.AnyColumn
import com.dbobjekts.api.AnyTable
import com.dbobjekts.api.TableRowData
import com.dbobjekts.metadata.Table
import com.dbobjekts.metadata.column.LongColumn
import com.dbobjekts.metadata.column.VarcharColumn
import com.dbobjekts.metadata.joins.JoinBase
import com.dbobjekts.metadata.joins.JoinType
import com.dbobjekts.metadata.joins.TableJoinChain
import com.dbobjekts.statement.WriteQueryAccessors
import com.dbobjekts.statement.insert.InsertBuilderBase
import com.dbobjekts.statement.update.HasUpdateBuilder
import com.dbobjekts.statement.update.UpdateBuilderBase

/**           
 * Auto-generated metadata object for db table nation.guests.
 *
 * Do not edit this file manually! Always use [com.dbobjekts.codegen.CodeGenerator] when the metadata model is no longer in sync with the database.           
 *
 * Primary keys: guest_id
 *
 * Foreign keys to: 
 * References by: 
 */
object Guests:Table<GuestsRow>("guests"), HasUpdateBuilder<GuestsUpdateBuilder, GuestsInsertBuilder> {
    /**
     * Represents db column nation.guests.guest_id
     */
    val guestId = LongColumn(this, "guest_id")
    /**
     * Represents db column nation.guests.name
     */
    val name = VarcharColumn(this, "name")
    override val columns: List<AnyColumn> = listOf(guestId,name)
    override fun toValue(values: List<Any?>) = GuestsRow(values[0] as Long,values[1] as String)
    override fun metadata(): WriteQueryAccessors<GuestsUpdateBuilder, GuestsInsertBuilder> = WriteQueryAccessors(GuestsUpdateBuilder(), GuestsInsertBuilder())

}

class GuestsJoinChain(table: AnyTable, joins: List<JoinBase> = listOf()) : TableJoinChain(table, joins) {
    
}


class GuestsUpdateBuilder() : UpdateBuilderBase(Guests) {
    fun guestId(value: Long): GuestsUpdateBuilder = put(Guests.guestId, value)
    fun name(value: String): GuestsUpdateBuilder = put(Guests.name, value)
    
    /**
     * FOR INTERNAL USE ONLY
     */
    override fun updateRow(rowData: TableRowData<*, *>): Long {
      rowData as GuestsRow
      add(Guests.guestId, rowData.guestId)
      add(Guests.name, rowData.name)
      return where(Guests.guestId.eq(rowData.guestId))
    }    
        
}

class GuestsInsertBuilder():InsertBuilderBase(){
    fun guestId(value: Long): GuestsInsertBuilder = put(Guests.guestId, value)
    fun name(value: String): GuestsInsertBuilder = put(Guests.name, value)

    fun mandatoryColumns(guestId: Long, name: String) : GuestsInsertBuilder {
      mandatory(Guests.guestId, guestId)
      mandatory(Guests.name, name)
      return this
    }


    override fun insertRow(rowData: TableRowData<*, *>): Long {
      rowData as GuestsRow
      add(Guests.guestId, rowData.guestId)
      add(Guests.name, rowData.name)
      return execute()
    }    
        
}


data class GuestsRow(
  val guestId: Long,
  val name: String    
) : TableRowData<GuestsUpdateBuilder, GuestsInsertBuilder>(Guests.metadata()){
     override val primaryKeys = listOf<Pair<AnyColumn, Any?>>(Pair(Guests.guestId, guestId))
}
        
