package com.dbobjekts.mariadb.testdb.nation
import com.dbobjekts.metadata.Schema

/**            
 * Auto-generated metadata object representing a schema consisting of one or more tables.
 *
 * Do not edit this file manually! Always use [com.dbobjekts.codegen.CodeGenerator] when the metadata model is no longer in sync with the database.             
*/
object Nation : Schema("nation", listOf(Continents, Countries, CountryLanguages, CountryStats, Guests, Languages, Regions, RegionAreas, Vips)){

    /** 
     * Refers to metadata object for table continents 
     */
    val continents = Continents
        
    /** 
     * Refers to metadata object for table countries 
     */
    val countries = Countries
        
    /** 
     * Refers to metadata object for table country_languages 
     */
    val countryLanguages = CountryLanguages
        
    /** 
     * Refers to metadata object for table country_stats 
     */
    val countryStats = CountryStats
        
    /** 
     * Refers to metadata object for table guests 
     */
    val guests = Guests
        
    /** 
     * Refers to metadata object for table languages 
     */
    val languages = Languages
        
    /** 
     * Refers to metadata object for table regions 
     */
    val regions = Regions
        
    /** 
     * Refers to metadata object for table region_areas 
     */
    val regionAreas = RegionAreas
        
    /** 
     * Refers to metadata object for table vips 
     */
    val vips = Vips
        
}
      