package com.dbobjekts.postgresql.testdb.hr

import com.dbobjekts.api.AnyColumn
import com.dbobjekts.api.TableRowData
import com.dbobjekts.metadata.Table
import com.dbobjekts.metadata.column.VarcharColumn
import com.dbobjekts.statement.WriteQueryAccessors
import com.dbobjekts.statement.insert.InsertBuilderBase
import com.dbobjekts.statement.update.HasUpdateBuilder
import com.dbobjekts.statement.update.UpdateBuilderBase

/**           
 * Auto-generated metadata object for db table hr.hobby.
 *
 * Do not edit this file manually! Always use [com.dbobjekts.codegen.CodeGenerator] when the metadata model is no longer in sync with the database.           
 *
 * Primary keys: id
 *
 * Foreign keys to: 
 * References by: core.employee
 */
object Hobby:Table<HobbyRow>("hobby"), HasUpdateBuilder<HobbyUpdateBuilder, HobbyInsertBuilder> {
    /**
     * Represents db column hr.hobby.id
     */
    val id = VarcharColumn(this, "id")
    /**
     * Represents db column hr.hobby.name
     */
    val name = VarcharColumn(this, "name")
    override val columns: List<AnyColumn> = listOf(id,name)
    override fun toValue(values: List<Any?>) = HobbyRow(values[0] as String,values[1] as String)
    override fun metadata(): WriteQueryAccessors<HobbyUpdateBuilder, HobbyInsertBuilder> = WriteQueryAccessors(HobbyUpdateBuilder(), HobbyInsertBuilder())
}

class HobbyUpdateBuilder() : UpdateBuilderBase(Hobby) {
    fun id(value: String): HobbyUpdateBuilder = put(Hobby.id, value)
    fun name(value: String): HobbyUpdateBuilder = put(Hobby.name, value)
    
    /**
     * FOR INTERNAL USE ONLY
     */
    override fun updateRow(rowData: TableRowData<*, *>): Long {
      rowData as HobbyRow
      add(Hobby.id, rowData.id)
      add(Hobby.name, rowData.name)
      return where(Hobby.id.eq(rowData.id))
    }    
        
}

class HobbyInsertBuilder():InsertBuilderBase(){
    fun id(value: String): HobbyInsertBuilder = put(Hobby.id, value)
    fun name(value: String): HobbyInsertBuilder = put(Hobby.name, value)

    fun mandatoryColumns(id: String, name: String) : HobbyInsertBuilder {
      mandatory(Hobby.id, id)
      mandatory(Hobby.name, name)
      return this
    }


    override fun insertRow(rowData: TableRowData<*, *>): Long {
      rowData as HobbyRow
      add(Hobby.id, rowData.id)
      add(Hobby.name, rowData.name)
      return execute()
    }    
        
}


data class HobbyRow(
  val id: String,
  val name: String    
) : TableRowData<HobbyUpdateBuilder, HobbyInsertBuilder>(Hobby.metadata()){
     override val primaryKeys = listOf<Pair<AnyColumn, Any?>>(Pair(Hobby.id, id))
}
        
