package com.dbobjekts.testdb.acme
import com.dbobjekts.testdb.acme.core.Address
import com.dbobjekts.testdb.acme.core.AllTypes
import com.dbobjekts.testdb.acme.core.Country
import com.dbobjekts.testdb.acme.core.Department
import com.dbobjekts.testdb.acme.core.Employee
import com.dbobjekts.testdb.acme.core.EmployeeAddress
import com.dbobjekts.testdb.acme.core.EmployeeDepartment
import com.dbobjekts.testdb.acme.hr.Certificate
import com.dbobjekts.testdb.acme.hr.Hobby
import com.dbobjekts.testdb.acme.library.Author
import com.dbobjekts.testdb.acme.library.Book
import com.dbobjekts.testdb.acme.library.Item
import com.dbobjekts.testdb.acme.library.Loan
import com.dbobjekts.testdb.acme.library.Member

/**  
 * Auto-generated metadata object. Provides a list of unique aliases for each table across all schemas in the catalog. These are used in the SQL that db-Objekts generates.
 *
 * Do not edit this file manually! Always use [com.dbobjekts.codegen.CodeGenerator] when the metadata model is no longer in sync with the database.
 *
 * You can import the individual values of in this object in your code to use them as convenient shortcuts.
 *
 * ```
 * import com.dbobjekts.testdb.acme.Aliases.e
 * [...]
 * transaction.select(e.name)
 *```
 */        
object Aliases {
    val a = Address
    val at = AllTypes
    val c = Country
    val d = Department
    val e = Employee
    val ea = EmployeeAddress
    val ed = EmployeeDepartment
    val c1 = Certificate
    val h = Hobby
    val a1 = Author
    val b = Book
    val i = Item
    val l = Loan
    val m = Member
}
     