package com.dbobjekts.testdb.acme
import com.dbobjekts.testdb.acme.core.Address
import com.dbobjekts.testdb.acme.core.AllTypes
import com.dbobjekts.testdb.acme.core.Country
import com.dbobjekts.testdb.acme.core.Department
import com.dbobjekts.testdb.acme.core.Employee
import com.dbobjekts.testdb.acme.core.EmployeeAddress
import com.dbobjekts.testdb.acme.core.EmployeeDepartment
import com.dbobjekts.testdb.acme.hr.Certificate
import com.dbobjekts.testdb.acme.hr.Hobby
import com.dbobjekts.testdb.acme.library.Author
import com.dbobjekts.testdb.acme.library.Book
import com.dbobjekts.testdb.acme.library.BookReview
import com.dbobjekts.testdb.acme.library.Composite
import com.dbobjekts.testdb.acme.library.CompositeForeignKey
import com.dbobjekts.testdb.acme.library.Item
import com.dbobjekts.testdb.acme.library.Loan
import com.dbobjekts.testdb.acme.library.Member

/**  
 * Auto-generated metadata object. Provides a list of unique aliases for each table across all schemas in the catalog. These are used in the SQL that db-Objekts generates.
 *
 * Do not edit this file manually! Always use [com.dbobjekts.codegen.CodeGenerator] when the metadata model is no longer in sync with the database.
 *
 * You can import the individual values of in this object in your code to use them as convenient shortcuts.
 *
 * ```
 * import com.dbobjekts.testdb.acme.Aliases.e
 * [...]
 * transaction.select(e.name)
 *```
 */        
object Aliases : HasAliases {
    override val ad = Address
    override val at = AllTypes
    override val co = Country
    override val de = Department
    override val em = Employee
    override val ea = EmployeeAddress
    override val ed = EmployeeDepartment
    override val ce = Certificate
    override val ho = Hobby
    override val au = Author
    override val bo = Book
    override val br = BookReview
    override val co1 = Composite
    override val cfk = CompositeForeignKey
    override val it1 = Item
    override val lo = Loan
    override val me = Member
}

/**  
 * Auto-generated metadata object. Interface for a list of unique aliases for each table across all schemas in the catalog.
 *
 * Do not edit this file manually! Always use [com.dbobjekts.codegen.CodeGenerator] when the metadata model is no longer in sync with the database.
 *
 * Any class can extends this interface and delegate to the Aliases object. This imports all the shortcuts without the need for separate manual import statements 
 *
 * ```
 * import com.dbobjekts.testdb.acme.Aliases
 * import com.dbobjekts.testdb.acme.HasAliases
 * [...]
 * class AcmeDbInteractions : HasAliases by Aliases {
 *  transaction.select(e.name, a.id, ea.kind)
 * }
 *```
 */ 
interface HasAliases {
    val ad : Address
    val at : AllTypes
    val co : Country
    val de : Department
    val em : Employee
    val ea : EmployeeAddress
    val ed : EmployeeDepartment
    val ce : Certificate
    val ho : Hobby
    val au : Author
    val bo : Book
    val br : BookReview
    val co1 : Composite
    val cfk : CompositeForeignKey
    val it1 : Item
    val lo : Loan
    val me : Member
}
     