package com.dbobjekts.testdb.acme
import com.dbobjekts.metadata.Catalog
import com.dbobjekts.testdb.acme.core.Core
import com.dbobjekts.testdb.acme.hr.Hr
import com.dbobjekts.testdb.acme.library.Library
/**
 * Auto-generated metadata object representing a database consisting of one or more schemas.
 *
 * Do not edit this file manually! Always use [com.dbobjekts.codegen.CodeGenerator] when the metadata model is no longer in sync with the database.
 *
 * A Catalog implementation provides access to all the metadata of a database and must be supplied to the `TransactionManager` upon configuration. 
 */
object CatalogDefinition : Catalog(0, "H2", listOf(Core, Hr, Library))