package com.dbobjekts.postgresql.testdb
import com.dbobjekts.postgresql.testdb.core.Address
import com.dbobjekts.postgresql.testdb.core.AllTypesNil
import com.dbobjekts.postgresql.testdb.core.Composite
import com.dbobjekts.postgresql.testdb.core.CompositeForeignKey
import com.dbobjekts.postgresql.testdb.core.Country
import com.dbobjekts.postgresql.testdb.core.Department
import com.dbobjekts.postgresql.testdb.core.Employee
import com.dbobjekts.postgresql.testdb.core.EmployeeAddress
import com.dbobjekts.postgresql.testdb.core.EmployeeDepartment
import com.dbobjekts.postgresql.testdb.hr.Certificate
import com.dbobjekts.postgresql.testdb.hr.Hobby

/**  
 * Auto-generated metadata object. Provides a list of unique aliases for each table across all schemas in the catalog. These are used in the SQL that db-Objekts generates.
 *
 * Do not edit this file manually! Always use [com.dbobjekts.codegen.CodeGenerator] when the metadata model is no longer in sync with the database.
 *
 * You can import the individual values of in this object in your code to use them as convenient shortcuts.
 *
 * ```
 * import com.dbobjekts.postgresql.testdb.Aliases.e
 * [...]
 * transaction.select(e.name)
 *```
 */        
object Aliases : HasAliases {
    override val ad = Address
    override val atn = AllTypesNil
    override val co = Composite
    override val cfk = CompositeForeignKey
    override val co1 = Country
    override val de = Department
    override val em = Employee
    override val ea = EmployeeAddress
    override val ed = EmployeeDepartment
    override val ce = Certificate
    override val ho = Hobby
}

/**  
 * Auto-generated metadata object. Interface for a list of unique aliases for each table across all schemas in the catalog.
 *
 * Do not edit this file manually! Always use [com.dbobjekts.codegen.CodeGenerator] when the metadata model is no longer in sync with the database.
 *
 * Any class can extends this interface and delegate to the Aliases object. This imports all the shortcuts without the need for separate manual import statements 
 *
 * ```
 * import com.dbobjekts.postgresql.testdb.Aliases
 * import com.dbobjekts.postgresql.testdb.HasAliases
 * [...]
 * class AcmeDbInteractions : HasAliases by Aliases {
 *  transaction.select(e.name, a.id, ea.kind)
 * }
 *```
 */ 
interface HasAliases {
    val ad : Address
    val atn : AllTypesNil
    val co : Composite
    val cfk : CompositeForeignKey
    val co1 : Country
    val de : Department
    val em : Employee
    val ea : EmployeeAddress
    val ed : EmployeeDepartment
    val ce : Certificate
    val ho : Hobby
}
     