package com.dbobjekts.codegen.writer

import com.dbobjekts.codegen.metadata.DBCatalogDefinition
import com.dbobjekts.util.Version

class CatalogSourceBuilder(val catalog: DBCatalogDefinition) {
    private val strBuilder = StringBuilder()

    fun createFileSource(): String {
        strBuilder.append("package ${catalog.packageName}\n")
        strBuilder.append("import com.dbobjekts.metadata.Catalog\n")
        catalog.schemas.forEach { strBuilder.append("import ${it.fullyQualifiedClassName()}\n") }

        strBuilder.append(createObjectBody())
        return strBuilder.toString()
    }

    private fun createObjectBody(): String {
        val schemas = catalog.schemas.map { it.asClassName() }.joinToString(", ")
        return """
           /**
            * Auto-generated metadata object representing a database consisting of one or more schemas.
            *
            * Do not edit this file manually! Always use [com.dbobjekts.codegen.CodeGenerator] when the metadata model is no longer in sync with the database.
            *
            * A Catalog implementation provides access to all the metadata of a database and must be supplied to the `TransactionManager` upon configuration. 
            */
           object ${catalog.asClassName()} : Catalog(${Version.MAJOR}, "${catalog.vendor.name}", listOf($schemas))
       """.trimIndent()

    }

}
