package com.dbobjekts.api

import com.dbobjekts.metadata.column.IsGeneratedPrimaryKey
import com.dbobjekts.statement.WriteQueryAccessors
import com.dbobjekts.statement.insert.InsertBuilderBase
import com.dbobjekts.statement.update.UpdateBuilderBase

abstract class TableRowData<U : UpdateBuilderBase, I : InsertBuilderBase>(
    internal val writeAccessors: WriteQueryAccessors<U, I>
) {
    abstract val primaryKeys: List<Pair<AnyColumn, Any?>>
    internal fun hasGeneratedPrimaryKey(): Boolean = primaryKeys.any { it.first is IsGeneratedPrimaryKey }
    internal fun getAutoGeneratedPkValue(): Long = if (hasGeneratedPrimaryKey()) primaryKeys.first().second.toString().toLong() else 0
}
